modLoader="lowcodefml"
loaderVersion="[1,)"
license="Unlicense"

[[mods]]
modId="bongowongo"
version="1.0"
displayName="BongoWongo"
description="Bongo Wongo custom additions"
authors="Pufferfish's Template Generator"